name: Deploy to Netlify
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: gamerlab - Netlify
      url: https://gamerlab.netlify.app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Netlify
        run: |
          # Add your deployment steps here
